on:
  workflow_dispatch:
  push:
    branches: main

name: Quarto Publish
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
   
      - name: Setup PDM
        uses: pdm-project/setup-pdm@v4
        # You are now able to use PDM in your workflow
      - name: Install dependencies
        run: |
          mkdir .venv
          python -m venv .venv
          source .venv/bin/activate
          which python
          pdm install
      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
      - name: Render and Publish
        run: |
          source .venv/bin/activate
          git config --global user.email "rishacha.dev@gmail.com"
          git config --global user.name "rishacha-quarto"
          quarto publish gh-pages . --no-browser
          
